.PHONY: clean All

All:
	@echo "----------Building project:[ ejemplo04 - Debug ]----------"
	@cd "ejemplo04" && "$(MAKE)" -f  "ejemplo04.mk"
clean:
	@echo "----------Cleaning project:[ ejemplo04 - Debug ]----------"
	@cd "ejemplo04" && "$(MAKE)" -f  "ejemplo04.mk" clean
